apiVersion: v1
kind: Secret
metadata:
  name: gestorong-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  POSTGRES_USER: gestorong
  POSTGRES_PASSWORD: troque-esta-senha
  POSTGRES_DB: conexaosolidaria

  MONGO_INITDB_ROOT_USERNAME: gestorong
  MONGO_INITDB_ROOT_PASSWORD: troque-esta-senha

  RABBITMQ_DEFAULT_USER: gestorong
  RABBITMQ_DEFAULT_PASS: troque-esta-senha

  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=conexaosolidaria;Username=gestorong;Password=troque-esta-senha"
  Mongo__ConnectionString: "mongodb://gestorong:troque-esta-senha@mongo:27017/?authSource=admin"
  RabbitMq__Usuario: gestorong
  RabbitMq__Senha: troque-esta-senha

  Jwt__ChaveSecreta: "troque-por-uma-chave-de-no-minimo-32-caracteres"

  Seed__GestorSenha: troque-esta-senha

  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: troque-esta-senha
